name: Install dependencies

description: Install node and pnpm, then run pnpm install

runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@v3
      with:
        version: 8
        run_install: true
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        cache: pnpm
        node-version-file: .nvmrc